# Generated by Django 4.0 on 2022-01-02 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firmware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headers', models.CharField(max_length=1000)),
                ('link', models.CharField(max_length=500)),
                ('filename', models.CharField(max_length=500)),
                ('firmware_version', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=500)),
                ('content', models.CharField(max_length=500)),
                ('meta_title', models.CharField(max_length=100)),
                ('meta_description', models.CharField(max_length=500)),
                ('medifire_link', models.CharField(max_length=1000)),
                ('gdrive_link', models.CharField(max_length=1000)),
                ('megadrive_link', models.CharField(max_length=1000)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('firmware_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.firmware')),
            ],
        ),
    ]
