# Generated by Django 4.0 on 2022-01-02 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmware',
            name='model',
            field=models.CharField(default='SM-N975F', max_length=100),
        ),
        migrations.AddField(
            model_name='firmware',
            name='region',
            field=models.CharField(default='INS', max_length=100),
        ),
    ]
