# Generated by Django 4.0 on 2022-01-02 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_firmware_model_firmware_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmware',
            name='headers',
            field=models.JSONField(default=''),
        ),
    ]
