# Generated by Django 4.0 on 2022-01-02 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_firmware_headers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmware',
            name='headers',
            field=models.JSONField(),
        ),
    ]
