# Generated by Django 4.0 on 2022-01-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_firmware_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmware',
            name='status',
            field=models.CharField(default='found', max_length=10),
        ),
    ]
